# Valores para FastAPI
replicaCount: 1

image:
  repository: ghcr.io/evaristogz/fastapi-ci-cd
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-creds

service:
  type: ClusterIP  # Cambiar a LoadBalancer para IP externa
  port: 80
  targetPort: 8000

# Para habilitar ingress (opcional)
ingress:
  enabled: false  # Cambiar a true para habilitar
  host: fastapi.local  # Cambiar por tu dominio

# Configuraciones opcionales (simplificadas)
resources: {}
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}

# Autoscaling deshabilitado por simplicidad
autoscaling:
  enabled: false

