# Valores para FastAPI
replicaCount: 1

image:
  repository: ghcr.io/evaristogz/fastapi-ci-cd
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-creds

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

# Configuraciones opcionales (simplificadas)
resources: {}
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}

# Autoscaling deshabilitado por simplicidad
autoscaling:
  enabled: false

